### ISSUE TITLE
Cython module

### ISSUE THREAD

**Issue by KongFulu** [Open3DA/LL3DA#26]
Thanks for the great work, how do I solve the following problem ：
(3DCLLM) kongfulu@Win202407091428:/mnt/e/project/LL3DA-main$ bash scripts/opt-1.3b/eval.generalist.sh
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
True
Could not import cythonized box intersection. Consider compiling box_intersection.pyx for faster training.
W0924 21:11:35.021575 139921442776896 torch/multiprocessing/spawn.py:146] Terminating process 94 via signal SIGTERM
W0924 21:11:35.021949 139921442776896 torch/multiprocessing/spawn.py:146] Terminating process 97 via signal SIGTERM
W0924 21:11:35.022014 139921442776896 torch/multiprocessing/spawn.py:146] Terminating process 98 via signal SIGTERM
W0924 21:11:35.022055 139921442776896 torch/multiprocessing/spawn.py:146] Terminating process 99 via signal SIGTERM
W0924 21:11:35.022102 139921442776896 torch/multiprocessing/spawn.py:146] Terminating process 101 via signal SIGTERM
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    launch_distributed(args)
  File "main.py", line 316, in launch_distributed
    torch.multiprocessing.spawn(main, nprocs=world_size, args=(args,))
  File "/home/kongfulu/anaconda3/envs/3DCLLM/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 282, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/kongfulu/anaconda3/envs/3DCLLM/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
    while not context.join():
  File "/home/kongfulu/anaconda3/envs/3DCLLM/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/kongfulu/anaconda3/envs/3DCLLM/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    fn(i, *args)
  File "/mnt/e/project/LL3DA-main/main.py", line 193, in main
    init_distributed(
TypeError: 'bool' object is not callable

**Comment by ch3cook-fdu** [comment]
``` 
cd utils
python cython_compile.py build_ext --inplace
```
