### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by kuaileqipaoshui** [Open3DA/LL3DA#5]
How long it takes you to train?

**Comment by ch3cook-fdu** [comment]
The training time takes about a day or two depending on your devices. The evaluation time takes much longer. You can track the training process using the logged output.

**Comment by kuaileqipaoshui** [comment]
> The training time takes about a day or two depending on your devices. The evaluation time takes much longer. You can track the training process using the logged output.

 Thanks! Does a day or two days include the tune time?

**Comment by ch3cook-fdu** [comment]
Not included. The tuning time usually takes less than a day.

**Comment by kuaileqipaoshui** [comment]
> Not included. The tuning time usually takes less than a day.

Thanks very much! When I try to train, I meet a problem, that is 

Original Traceback (most recent call last):
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/private/LL3DA/datasets/unified_3dllm_scene_description.py", line 135, in __getitem__
    ret_dict['box_query'] = box_query.astype(np.float32)
TypeError: 'NoneType' object does not support item assignment

I don't know how to solve it. How could I fix it?

**Comment by ch3cook-fdu** [comment]
You should check whether you have processed the scene data right and loaded the scene data properly in `ret_dict`.

**Comment by kuaileqipaoshui** [comment]
File "/data/private/LL3DA/main.py", line 299, in main
    do_train(
  File "/data/private/LL3DA/engine.py", line 160, in do_train
    task_metrics = test_loader.dataset.eval_func(
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/private/LL3DA/eval_utils/evaluate_qa.py", line 123, in evaluate
    outputs = model(model_input, is_eval=True, task_name='qa')
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/LL3DA/models/model_general.py", line 56, in forward
    outputs = self.captioner(
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/LL3DA/models/ll3da/captioner.py", line 300, in forward
    return self.predict_answer(detector_output, inputs, max_gen_length=max_gen_length)
  File "/data/private/LL3DA/models/ll3da/captioner.py", line 441, in predict_answer
    output = generation(
  File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 212, in generation
    outputs = beam_search_decode(transformer, **kwargs)
  File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 156, in beam_search_decode
    output_ids = torch.cat([
  File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 158, in <listcomp>
    [
  File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 159, in <listcomp>
    beam_sentence.unsqueeze(0) \
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

**Comment by kuaileqipaoshui** [comment]
> You should check whether you have processed the scene data right and loaded the scene data properly in `ret_dict`.

Thanks! How about this problem?

File "/data/private/LL3DA/main.py", line 299, in main
do_train(
File "/data/private/LL3DA/engine.py", line 160, in do_train
task_metrics = test_loader.dataset.eval_func(
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/data/private/LL3DA/eval_utils/evaluate_qa.py", line 123, in evaluate
outputs = model(model_input, is_eval=True, task_name='qa')
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
output = self._run_ddp_forward(*inputs, **kwargs)
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
return module_to_run(*inputs[0], **kwargs[0])
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/data/private/LL3DA/models/model_general.py", line 56, in forward
outputs = self.captioner(
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/data/private/LL3DA/models/ll3da/captioner.py", line 300, in forward
return self.predict_answer(detector_output, inputs, max_gen_length=max_gen_length)
File "/data/private/LL3DA/models/ll3da/captioner.py", line 441, in predict_answer
output = generation(
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 212, in generation
outputs = beam_search_decode(transformer, **kwargs)
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 156, in beam_search_decode
output_ids = torch.cat([
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 158, in
[
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 159, in
beam_sentence.unsqueeze(0)
AttributeError: 'NoneType' object has no attribute 'unsqueeze'
